In [13]:
import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as widgets

In [22]:
from ipywidgets import interact

t = np.arange(0.0, 1.0, 0.01)

def pltsin(f):
    plt.plot(t, np.tanh(2*np.pi*t*f))
    plt.show()
    
interact(pltsin, f = (1,10,0.1))

interactive(children=(FloatSlider(value=5.0, description='f', max=10.0, min=1.0), Output()), _dom_classes=('widget-interact',))

<function __main__.pltsin>

In [14]:
widgets.IntSlider()

IntSlider(value=0)

In [2]:
a = np.arange(36).reshape(12,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]
 [30 31 32]
 [33 34 35]]


In [3]:
print("Shape: {} N_Dim: {} Size: {} Type: {}".format(a.shape, a.ndim, a.size, type(a)))

Shape: (12, 3) N_Dim: 2 Size: 36 Type: <class 'numpy.ndarray'>


# Ways to create Arrays

In [4]:
a = np.array([2,3,4])
print(a, a.dtype)
b = np.array([2.,3.,4.])
print(b, b.dtype)
# Sequence of sequence => 2D array
c = np.array([[1,2,3], [4,5,6]])
print('\nSequence of sequences:\n\n{}'.format(c))
# Explicit data type
d = np.array([[1,2],[3,4]], dtype=complex)
print('\nExplicit data type:\n\n{}'.format(d))

[2 3 4] int32
[2. 3. 4.] float64

Sequence of sequences:

[[1 2 3]
 [4 5 6]]

Explicit data type:

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


## Placeholders

In [5]:
print(np.zeros((2,3), dtype = np.float64))
print(np.ones((5,6), dtype=np.complex))
print(np.empty((5,6), dtype=np.int16))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]]
[[     0      0      0      0   1000      0]
 [     0      0      5      0      0      0]
 [ -1552 -19914    526      0      0      0]
 [     0      0      7      3      0      0]
 [ -6880 -19997    526      0      0      0]]


## Create sequences of array type

In [6]:
def out(rng):
    print('\nRange:\n\n{}\n\n'.format(rng))
out(np.arange(10, 30, 5))
out(np.arange(40))
out(np.arange(1,12.5,2.5))



Range:

[10 15 20 25]



Range:

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]



Range:

[ 1.   3.5  6.   8.5 11. ]




But arange gives an unpredictably sized output cos of floating point arithmetic, so do this instead:

In [7]:
lin = np.linspace(0,2,9) # 9 numbers from 0 to 2
print(lin)

# Let's evaluate tan at a bunch of points...
print('\nTan over [0,pi/2]:\n\n')
domain = np.linspace(0, np.pi/2, 100)
print(np.tan(domain))

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]

Tan over [0,pi/2]:


[0.00000000e+00 1.58679612e-02 3.17439152e-02 4.76358711e-02
 6.35518701e-02 7.95000022e-02 9.54884223e-02 1.11525367e-01
 1.27619174e-01 1.43778294e-01 1.60011316e-01 1.76326981e-01
 1.92734202e-01 2.09242088e-01 2.25859960e-01 2.42597375e-01
 2.59464150e-01 2.76470386e-01 2.93626493e-01 3.10943217e-01
 3.28431672e-01 3.46103365e-01 3.63970234e-01 3.82044681e-01
 4.00339609e-01 4.18868463e-01 4.37645272e-01 4.56684698e-01
 4.76002082e-01 4.95613502e-01 5.15535831e-01 5.35786798e-01
 5.56385058e-01 5.77350269e-01 5.98703173e-01 6.20465681e-01
 6.42660977e-01 6.65313620e-01 6.88449662e-01 7.12096776e-01
 7.36284401e-01 7.61043891e-01 7.86408692e-01 8.12414533e-01
 8.39099631e-01 8.66504933e-01 8.94674368e-01 9.23655146e-01
 9.53498074e-01 9.84257927e-01 1.01599385e+00 1.04876982e+00
 1.08265515e+00 1.11772510e+00 1.15406152e+00 1.19175359e+00
 1.23089871e+00 1.27160344e+00 1.31398466e+00 1.35817084e+00
 1.40430351e+00 

# Operations

In [8]:
a = np.array([20,30,40,50])
b = np.arange(4)
print('a is: {}\nb is: {}\na-b is: {}\nb**2 is:{}\na <35 is:{}'.format(a,b,a-b, b**2, a<35))

a is: [20 30 40 50]
b is: [0 1 2 3]
a-b is: [20 29 38 47]
b**2 is:[0 1 4 9]
a <35 is:[ True  True False False]


Matrix multiplication:

In [9]:
A = np.arange(4).reshape(2,2)
B = np.arange(4, 11, 2).reshape(2,2)
print('A is \n{}\nB is \n{}\n A * B is\n{}\n A.dot(B) is\n{}'.format(A, B, A*B, A.dot(B)))
# Or you can write np.dot(A,B)

A is 
[[0 1]
 [2 3]]
B is 
[[ 4  6]
 [ 8 10]]
 A * B is
[[ 0  6]
 [16 30]]
 A.dot(B) is
[[ 8 10]
 [32 42]]


Reductions:

In [10]:
print('{}\n{}\n{}'.format(A.sum(), A.min(), A.max()))
print('Or you can sum, floating along a particular axis:\n')
print('Sum of columns of A:')
print(A.sum(axis=0)) # = [a00+a10, a01+a11], axis is the one that varies

6
0
3
Or you can sum, floating along a particular axis:

Sum of columns of A:
[2 4]


So what happens if it's a multi-dimensional matrix?

In [11]:
D = np.arange(27).reshape(3,3,3)
print('Starting matrix:')
print(D)
# D[a][b][c] = d_abc
print('\nSum over axis 0:')
print(D.sum(axis=0)) # = [[d000+d100+d200]... etc... 3x3 mtx generated by varying d_ijk over jk]
print('\nSum over axis 0, summed over axis 1:') # [e00 + e01 + e02, e10 + e11 + e12, etc]
# Prediction: [90, 117, 144]
print(D.sum(axis=0).sum(axis=1))

Starting matrix:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

Sum over axis 0:
[[27 30 33]
 [36 39 42]
 [45 48 51]]

Sum over axis 0, summed over axis 1:
[ 90 117 144]


## Shape Manipulation

In [12]:
a = np.floor(10*np.random.random((3,4)))
print(a)
# Doesn't change a...
b = a.ravel()
print(b)
print(a.reshape(6,2))
print(a.T)
print(a)
# Does change a...
a.resize((2,6))
print(a)
# Can leave a dimension implict (numPy does the factorization for us)
print(a.reshape(6,-1))

[[9. 2. 2. 8.]
 [3. 1. 8. 5.]
 [4. 4. 0. 8.]]
[9. 2. 2. 8. 3. 1. 8. 5. 4. 4. 0. 8.]
[[9. 2.]
 [2. 8.]
 [3. 1.]
 [8. 5.]
 [4. 4.]
 [0. 8.]]
[[9. 3. 4.]
 [2. 1. 4.]
 [2. 8. 0.]
 [8. 5. 8.]]
[[9. 2. 2. 8.]
 [3. 1. 8. 5.]
 [4. 4. 0. 8.]]
[[9. 2. 2. 8. 3. 1.]
 [8. 5. 4. 4. 0. 8.]]
[[9. 2.]
 [2. 8.]
 [3. 1.]
 [8. 5.]
 [4. 4.]
 [0. 8.]]


S